### ISSUE TITLE
Linear Search Algorithm and Code.

### ISSUE THREAD

**Issue by kashyap1905** [kashyap1905/DSA-Playlist-Collaboration#1]
Design an algorithm to implement linear search in an array of size N. Take size of array as input from user.

**Comment by AmitThakur045** [comment]
@kashyap1905  can you assign this to me

**Comment by kashyap1905** [comment]
Assigned @AmitThakur045

**Comment by kashyap1905** [comment]
Fixed by @AmitThakur045
