### ISSUE TITLE
Binary Search Algorithm and Code

### ISSUE THREAD

**Issue by kashyap1905** [kashyap1905/DSA-Playlist-Collaboration#2]
Design an algorithm to implement binary search in array of size N. Take the size of array as input from the user.

**Comment by AmitThakur045** [comment]
Hey @kashyap1905 can i implement the binary search

**Comment by kashyap1905** [comment]
@AmitThakur045 Assigned...

**Comment by kashyap1905** [comment]
Fixed by @AmitThakur045
